[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#F43F5E"
backgroundColor = "#090A0F"
secondaryBackgroundColor = "#12141C"
textColor = "#F3F4F6"
font = "sans serif"
